#!/usr/bin/env python
#Copyright 20 Erik Tollerud
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.

from optparse import OptionParser
from astropysics import config

parser = OptionParser()
parser.add_option("-p", "--no-package-install", dest="install", 
                  help="Skip the installation tool.",
                  action="store_false",default=True)
parser.add_option("-i", "--no-ipython", dest="ipython", 
                  help="Skip the ipython setup tool.",
                  action="store_false",default=True)
parser.add_option("-s", "--sudo", dest="sudo", 
                  help="Runs the install step prefixed by 'sudo' (or turns sudo *off* if this platform normally expects to use sudo).",
                  action="store_true",default=False)

ops, args = parser.parse_args()

if ops.install:
    config.run_install_tool(sudo='toggleauto' if ops.sudo else 'auto')
    
if ops.ipython:
    config.run_ipython_setup()
