#!/usr/bin/env python

import sys,IPython

if __name__ == '__main__':
    #insert necessary ipython arguments if they aren't already there
    
    sys.argv.append('-p')
    sys.argv.append('astpys')
    
    #get version info
    majver,minver = IPython.__version__.split('.')[:2]
    majver,minver = int(majver),int(minver)
    
    if majver>0 or minver>=11:
        #Use entry point mechanism
        from pkg_resources import load_entry_point
        sys.exit(load_entry_point('ipython', 'console_scripts', 'ipython')())
    else:
        #add pylab if version < 0.11,
        if '--pylab' not in sys.argv:
            sys.argv.append('--pylab')
        
        #Launch via the .start mechanism
        import IPython.Shell
        IPython.Shell.start().mainloop()
    
    
    