#!/usr/bin/env python
#Copyright 2009 Erik Tollerud
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.

from sys import argv
from astropysics.publication import *

if len(argv) > 1:
    al=argv[1].lower()
    if al == 'apj':
        print 'prepping for apj publication'
        prep_for_apj_pub()
    elif al == 'arxiv':
        print 'prepping for arXiv publication'
        prep_for_arxiv_pub()
    else:
        print 'unrecognized journal type, doing nothing'